export const keycodes = [
  { sequence: '\r', shortcut: 'return' },
  { sequence: '\x03', shortcut: 'ctrl+c', ctrl: true },

  { sequence: '\x1C', shortcut: 'ctrl+4', ctrl: true },
  { sequence: '\x1D', shortcut: 'ctrl+5', ctrl: true },
  { sequence: '\x1E', shortcut: 'ctrl+6', ctrl: true },
  { sequence: '\x1F', shortcut: 'ctrl+7', ctrl: true },

  { sequence: '\x1B[1;10A', shortcut: 'shift+meta+up', code: '[1;10A', name: 'up', meta: true, shift: true },
  { sequence: '\x1B[1;10B', shortcut: 'shift+meta+down', code: '[1;10B', name: 'down', meta: true, shift: true },
  { sequence: '\x1B[1;10C', shortcut: 'shift+meta+right', code: '[1;10C', name: 'left', meta: true, shift: true },
  { sequence: '\x1B[1;10D', shortcut: 'shift+meta+left', code: '[1;10D', name: 'right', meta: true, shift: true },

  { sequence: '\x1B[1;2A', shortcut: 'shift+up', code: '[1;2A', shift: true },
  { sequence: '\x1B[1;2B', shortcut: 'shift+down', code: '[1;2B', shift: true },
  { sequence: '\x1B[1;2C', shortcut: 'shift+right', code: '[1;2C', shift: true },
  { sequence: '\x1B[1;2D', shortcut: 'shift+left', code: '[1;2D', shift: true },

  { sequence: '\x1B[1;2F', shortcut: 'fn+shift+right', code: '[1;2F', fn: true, shift: true },
  { sequence: '\x1B[1;2H', shortcut: 'fn+shift+left', code: '[1;2H', fn: true, shift: true },

  { sequence: '\x1B[1;9F', shortcut: 'fn+meta+right', code: '[1;9F', fn: true, meta: true },
  { sequence: '\x1B[1;9H', shortcut: 'fn+meta+left', code: '[1;9H', fn: true, meta: true },

  { sequence: '\x1B[1;10F', shortcut: 'fn+shift+meta+right', code: '[1;10F', name: 'right', fn: true, meta: true, shift: true },
  { sequence: '\x1B[1;10H', shortcut: 'fn+shift+meta+left', code: '[1;10H', name: 'left', fn: true, meta: true, shift: true },

  { sequence: '\x1B[11~', shortcut: 'f1', fn: true },
  { sequence: '\x1B[12~', shortcut: 'f2', fn: true },
  { sequence: '\x1B[13~', shortcut: 'f3', fn: true },
  { sequence: '\x1B[14~', shortcut: 'f4', fn: true },
  { sequence: '\x1B[15~', shortcut: 'f5', fn: true },
  { sequence: '\x1B[17~', shortcut: 'f6', fn: true },
  { sequence: '\x1B[18~', shortcut: 'f7', fn: true },
  { sequence: '\x1B[19~', shortcut: 'f8', fn: true },
  { sequence: '\x1B[20~', shortcut: 'f9', fn: true },
  { sequence: '\x1B[21~', shortcut: 'f10', fn: true },
  { sequence: '\x1B[23~', shortcut: 'f11', fn: true },
  { sequence: '\x1B[24~', shortcut: 'f12', fn: true },
  { sequence: '\x1B[25~', shortcut: 'f13', fn: true },
  { sequence: '\x1B[26~', shortcut: 'f14', fn: true },
  { sequence: '\x1B[28~', shortcut: 'f15', fn: true },
  { sequence: '\x1B[29~', shortcut: 'f16', fn: true },
  { sequence: '\x1B[31~', shortcut: 'f17', fn: true },
  { sequence: '\x1B[32~', shortcut: 'f18', fn: true },
  { sequence: '\x1B[33~', shortcut: 'f19', fn: true },
  { sequence: '\x1B[34~', shortcut: 'f20', fn: true },

  { sequence: '\x1BOP', shortcut: 'f1', fn: true },
  { sequence: '\x1BOQ', shortcut: 'f2', fn: true },
  { sequence: '\x1BOR', shortcut: 'f3', fn: true },
  { sequence: '\x1BOS', shortcut: 'f4', fn: true },

  { sequence: '\x1B\x1B[5~', shortcut: 'fn+meta+up', code: '[5~', meta: true, fn: true },
  { sequence: '\x1B\x1B[6~', shortcut: 'fn+meta+down', code: '[6~', meta: true, fn: true },
  { sequence: '\x1BOl', shortcut: 'num_key_comma' },
  { sequence: '\x1BOm', shortcut: 'num_key_minus' },
  { sequence: '\x1BOn', shortcut: 'num_key_period' },
  { sequence: '\x1BOp', shortcut: 'num_key_0' },
  { sequence: '\x1BOq', shortcut: 'num_key_1' },
  { sequence: '\x1BOr', shortcut: 'num_key_2' },
  { sequence: '\x1BOs', shortcut: 'num_key_3' },
  { sequence: '\x1BOt', shortcut: 'num_key_4' },
  { sequence: '\x1BOu', shortcut: 'num_key_5' },
  { sequence: '\x1BOv', shortcut: 'num_key_6' },
  { sequence: '\x1BOw', shortcut: 'num_key_7' },
  { sequence: '\x1BOx', shortcut: 'num_key_8' },
  { sequence: '\x1BOy', shortcut: 'num_key_9' }
];
